// apps/web/src/components/upstream-edit/CodexAccountCard.vue
<script setup lang="ts">
// Identity + state + quota summary for one Codex account in an upstream's
// pool. Pure presentational card — no API calls live here.

import { computed } from 'vue';

import type { CodexAccountCredentialState, CodexAccountIdentity, CodexQuotaSnapshot, UpstreamRecord } from '../../api/types.ts';
import { providerSwatchClass } from '../upstreams/provider-meta.ts';
import { Badge, Card } from '@floway-dev/ui';

const props = defineProps<{
  record: UpstreamRecord;
}>();

interface QuotaWindowView {
  label: string;
  percent?: number;
  resetAt?: string;
  windowMinutes?: number;
}

interface QuotaEntryView {
  key: string;
  label: string;
  quota: CodexQuotaSnapshot;
  rateLimitedUntil: string | null;
  windows: QuotaWindowView[];
}

// Narrow once: this card only renders inside a codex upstream's edit page.
// Pinning the narrow at the script-setup boundary lets every computed below
// reach `config` / `state` / `codex_quota` without `as` casts.
const codexRecord = computed(() => {
  if (props.record.kind !== 'codex') {
    throw new Error(`CodexAccountCard requires a codex upstream, got ${props.record.kind}`);
  }
  return props.record;
});

const account = computed<CodexAccountIdentity>(() => codexRecord.value.config.accounts[0]);

const credential = computed<CodexAccountCredentialState | null>(() => {
  const raw = codexRecord.value.state;
  if (!raw || !Array.isArray(raw.accounts)) return null;
  return raw.accounts.find(a => a.chatgptAccountId === account.value.chatgptAccountId) ?? null;
});

const quotaMap = computed(() => codexRecord.value.codex_quota ?? null);

const formatTimestamp = (iso: string): string => {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString();
};

const formatPercent = (n: number | undefined): string => {
  if (typeof n !== 'number' || !Number.isFinite(n)) return '—';
  return `${Math.max(0, Math.min(100, Math.round(n)))}%`;
};

const futureTimestamp = (iso: string | undefined, now: number): string | null => {
  if (typeof iso !== 'string') return null;
  return new Date(iso).getTime() > now ? iso : null;
};

const quotaEntries = computed<QuotaEntryView[]>(() => {
  const map = quotaMap.value;
  if (!map) return [];
  const now = Date.now();
  return Object.entries(map)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, quota]) => ({
      key,
      label: quota.active_limit ?? key,
      quota,
      rateLimitedUntil: futureTimestamp(quota.ratelimited_until, now),
      windows: [
        { label: 'Primary window', percent: quota.primary_used_percent, resetAt: quota.primary_reset_after_at, windowMinutes: quota.primary_window_minutes },
        { label: 'Secondary window', percent: quota.secondary_used_percent, resetAt: quota.secondary_reset_after_at, windowMinutes: quota.secondary_window_minutes },
      ],
    }));
});

const accountCredits = computed<CodexQuotaSnapshot | null>(() => {
  const map = quotaMap.value;
  if (!map) return null;
  let newest: CodexQuotaSnapshot | null = null;
  let newestObservedAt = Number.NEGATIVE_INFINITY;
  for (const quota of Object.values(map)) {
    if (quota.credits_balance === undefined && quota.credits_has_credits === undefined) continue;
    const observedAt = new Date(quota.observed_at).getTime();
    if (observedAt > newestObservedAt) {
      newest = quota;
      newestObservedAt = observedAt;
    }
  }
  return newest;
});

const badge = computed<{ tone: 'rose' | 'amber' | 'emerald'; label: string; detail?: string }>(() => {
  const c = credential.value;
  if (c?.state === 'session_terminated') {
    return { tone: 'rose', label: 'Session terminated — re-import to recover', detail: c.state_message };
  }
  if (c?.state === 'refresh_failed') {
    return { tone: 'rose', label: 'Refresh failed — re-import to recover', detail: c.state_message };
  }
  const rateLimitedUntil = quotaEntries.value
    .map(entry => entry.rateLimitedUntil)
    .filter((until): until is string => until !== null)
    .sort((a, b) => new Date(b).getTime() - new Date(a).getTime())[0];
  if (rateLimitedUntil) {
    return { tone: 'rose', label: `Rate-limited until ${formatTimestamp(rateLimitedUntil)}` };
  }
  const usages = quotaEntries.value
    .flatMap(entry => [entry.quota.primary_used_percent, entry.quota.secondary_used_percent])
    .filter((v): v is number => typeof v === 'number');
  const heaviest = usages.length ? Math.max(...usages) : null;
  if (heaviest !== null && heaviest >= 80) {
    return { tone: 'amber', label: `Heavy usage (${heaviest}%)` };
  }
  return { tone: 'emerald', label: 'Active' };
});

const accountIdShort = computed(() => {
  const id = account.value.chatgptAccountId;
  if (id.length <= 18) return id;
  return `${id.slice(0, 8)}…${id.slice(-6)}`;
});
</script>

<template>
  <Card :padded="false" class="space-y-4 p-4">
    <div class="flex items-start gap-3">
      <div class="flex size-10 shrink-0 items-center justify-center rounded-full" :class="providerSwatchClass('codex')">
        <i class="i-simple-icons-openai size-5" />
      </div>
      <div class="min-w-0 flex-1 space-y-1">
        <p class="truncate text-sm font-medium text-white">{{ account.email }}</p>
        <div class="flex flex-wrap items-center gap-2 text-xs text-gray-400">
          <Badge tone="violet" size="sm" class="!uppercase tracking-wide">{{ account.planType }}</Badge>
          <Badge v-if="accountCredits?.credits_has_credits === false" tone="rose" size="sm">no credits</Badge>
          <Badge v-else-if="accountCredits?.credits_balance !== undefined" tone="zinc" size="sm">
            credits: {{ accountCredits.credits_balance }}
          </Badge>
          <span class="font-mono text-[11px] text-gray-500" :title="account.chatgptAccountId">{{ accountIdShort }}</span>
        </div>
      </div>
      <Badge :tone="badge.tone" size="sm">{{ badge.label }}</Badge>
    </div>

    <p v-if="badge.detail" class="text-xs text-gray-500">{{ badge.detail }}</p>

    <template v-if="quotaEntries.length">
      <div class="space-y-3">
        <section v-for="entry in quotaEntries" :key="entry.key" class="space-y-3 rounded-xl border border-white/[0.06] bg-surface-900/40 p-3">
          <div class="flex min-w-0 items-baseline justify-between gap-3">
            <h4 class="min-w-0 truncate text-sm font-medium text-gray-200" :title="entry.label">{{ entry.label }}</h4>
            <span class="shrink-0 text-[11px] uppercase tracking-wide text-gray-500">active limit</span>
          </div>

          <div class="space-y-3">
            <div v-for="w in entry.windows" :key="`${entry.key}:${w.label}`" class="space-y-1">
              <div class="flex items-baseline justify-between text-xs">
                <span class="text-gray-300">{{ w.label }}</span>
                <span class="text-gray-500">
                  {{ formatPercent(w.percent) }}<template v-if="w.windowMinutes"> · {{ w.windowMinutes }} min window</template>
                </span>
              </div>
              <div class="h-1.5 overflow-hidden rounded-full bg-surface-700">
                <div
                  class="h-full bg-accent-violet transition-[width]"
                  :style="{ width: `${Math.max(0, Math.min(100, Math.round(w.percent ?? 0)))}%` }"
                />
              </div>
              <p v-if="w.resetAt" class="text-[11px] text-gray-500">Resets at {{ formatTimestamp(w.resetAt) }}</p>
            </div>
          </div>

          <footer class="flex flex-wrap items-center gap-3 border-t border-white/[0.06] pt-3 text-[11px] text-gray-500">
            <span v-if="entry.rateLimitedUntil">rate-limited until {{ formatTimestamp(entry.rateLimitedUntil) }}</span>
            <span>observed {{ formatTimestamp(entry.quota.observed_at) }}</span>
          </footer>
        </section>
      </div>

      <footer v-if="credential?.state_updated_at" class="border-t border-white/[0.06] pt-3 text-[11px] text-gray-500">
        state updated {{ formatTimestamp(credential.state_updated_at) }}
      </footer>
    </template>

    <p v-else class="text-xs text-gray-500">No quota snapshots yet. Make Codex calls to populate.</p>
  </Card>
</template>

// apps/web/src/components/upstream-editor/codex-account-card.tsx
import { useTranslation } from 'react-i18next';

import { shortAccountId } from './account-id';
import { accountStatus, type CodexRecord, findCredential, latestCredits, quotaEntries } from './codex-account';
import { quotaBarColor, WALL_CLOCK_REFRESH_MS } from './subscription-account-quota';
import { fluentComponents } from '../../fluent';
import { dateTime } from '../../lib/format-time';
import { clampPercent, percentText } from '../../lib/percent';
import { useLocale } from '../../lib/use-locale';
import { useNow } from '../../lib/use-now';
import { StatusBadge } from '../ui/status-badge';
import { ProviderIcon } from '../upstreams/provider-badge';

const { Badge, ProgressBar, Text, Tooltip } = fluentComponents;

export function CodexAccountCard({ record }: { record: CodexRecord }) {
  const { t } = useTranslation();
  const now = useNow(WALL_CLOCK_REFRESH_MS);
  const locale = useLocale();
  const account = record.config.accounts[0];
  const lookup = findCredential(record);
  const credential = lookup.kind === 'present' ? lookup.credential : null;
  const entries = quotaEntries(record.codex_quota, now);
  const credits = latestCredits(record.codex_quota);
  const status = accountStatus(lookup, entries);

  const statusLabel = status.reason === 'heavy'
    ? t('dashboard.upstreamEditor.codex.status.heavy', { percent: status.percent })
    : status.reason === 'rate-limited'
      ? t('dashboard.upstreamEditor.codex.status.rateLimited', { time: dateTime(status.until, locale) })
      : t(`dashboard.upstreamEditor.codex.status.${status.reason}`);

  return <section className="grid gap-4">
    <div className="flex items-start gap-3">
      <ProviderIcon kind="codex" className="h-8 w-8 shrink-0" />
      <div className="grid gap-1 min-w-0 flex-1">
        <Text block weight="semibold" truncate wrap={false}>{account.email}</Text>
        <div className="flex flex-wrap items-center gap-2">
          <StatusBadge tone="accent">{account.planType}</StatusBadge>
          {credits?.credits_has_credits === false
            ? <StatusBadge tone="danger">{t('dashboard.upstreamEditor.codex.noCredits')}</StatusBadge>
            : credits?.credits_balance !== undefined && <Badge appearance="outline" size="large">
              {t('dashboard.upstreamEditor.codex.credits', { balance: credits.credits_balance })}
            </Badge>}
          <Tooltip content={account.chatgptAccountId} relationship="description">
            <Text size={200} className="winui-focus-rect text-fui-fg3 font-mono mono-size-xs" tabIndex={0}>{shortAccountId(account.chatgptAccountId)}</Text>
          </Tooltip>
        </div>
      </div>
      <StatusBadge tone={status.tone}>{statusLabel}</StatusBadge>
    </div>

    {status.tone === 'danger' && status.detail && <Text size={200} className="text-fui-fg2">{status.detail}</Text>}

    {entries.length === 0
      ? <Text size={200} className="text-fui-fg3">{t('dashboard.upstreamEditor.codex.noSnapshot')}</Text>
      : entries.map(entry => <section className="grid gap-3 border-0 border-t border-solid border-fui-divider py-3 first:border-t-0" key={entry.key}>
          <div className="flex items-baseline justify-between gap-3 min-w-0">
            <Tooltip content={entry.label} relationship="label">
              <Text block className="winui-focus-rect" truncate weight="semibold" tabIndex={0} wrap={false}>{entry.label}</Text>
            </Tooltip>
            <Text size={200} className="text-fui-fg3 shrink-0 uppercase tracking-wide">{t('dashboard.upstreamEditor.codex.activeLimit')}</Text>
          </div>
          {entry.windows.map(item => {
            const percent = clampPercent(item.percent);
            return <div className="grid gap-1" key={item.key}>
              <div className="flex items-baseline justify-between gap-3">
                <Text size={200}>{t(`dashboard.upstreamEditor.codex.window.${item.key}`)}</Text>
                <div className="flex items-baseline gap-2">
                  <Text size={200} className="text-fui-fg2">{percentText(percent)}</Text>
                  {item.windowMinutes !== null && <Text size={200} className="text-fui-fg3">
                    {t('dashboard.upstreamEditor.codex.windowMinutes', { minutes: item.windowMinutes })}
                  </Text>}
                </div>
              </div>
              <ProgressBar color={quotaBarColor(percent)} max={100} thickness="large" value={percent ?? undefined} />
              {item.resetAt && <Text size={200} className="text-fui-fg3">
                {t('dashboard.upstreamEditor.codex.resetsAt', { time: dateTime(item.resetAt, locale) })}
              </Text>}
            </div>;
          })}
          <div className="flex flex-wrap gap-x-4 gap-y-1">
            {entry.rateLimitedUntil && <Text size={200} className="text-fui-fg3">
              {t('dashboard.upstreamEditor.codex.rateLimitedUntil', { time: dateTime(entry.rateLimitedUntil, locale) })}
            </Text>}
            <Text size={200} className="text-fui-fg3">{t('dashboard.upstreamEditor.codex.observed', { time: dateTime(entry.observedAt, locale) })}</Text>
          </div>
        </section>)}

    {credential?.state_updated_at && <Text size={200} className="text-fui-fg3 border-0 border-t border-solid border-fui-divider pt-3">
      {t('dashboard.upstreamEditor.codex.stateUpdated', { time: dateTime(credential.state_updated_at, locale) })}
    </Text>}
  </section>;
}
